### ISSUE TITLE
'Existing content' displayed separately of Nav

### ISSUE THREAD

**Issue by Ajaay** [artberri/sidr#106]
Hi,

When loading existing content into the side nav the content is still displayed when the menu is toggled off (keeping whatever CSS classes I have applied to that content). I have to apply CSS display: none to fix it. Any ideas why this is?

The second part to my question is regarding the renaming: false option. Should this still add custom .sidr classes to my nav? It appears to be applying some of my own CSS and some of the sidr CSS. And of course because of my problem where 'existing content' is displayed when the sidr nav is toggled off keeping my own css classes applied without anything hidden causes a full nav to be displayed on the screen at all times....

What I'm aiming for is to keep my own nav CSS and just have that nav toggling on and off ..... Is this possible?

Thanks!

**Comment by artberri** [comment]
Yes is possible. Show your code please.
