### ISSUE TITLE
Noob question

### ISSUE THREAD

**Issue by momekh** [artberri/sidr#111]
Great plugin. Dead tired from trying out different ones and this one worked right out of the box. Super useful. Thanks.

Now the question: I want the sidr menu to close when user clicks outside of it. Don't want the user to completely depend on the toggle. 

Help, anyone?

**Comment by tigertooth01** [comment]
Click propagation is still an issue @momekh, you see, when you click anywhere outside the menu, you'd possibly be clicking a link/button on the main html, that click event also gets triggered while trying to close the menu. Any way to prevent that?

**Comment by artberri** [comment]
Stackoverflow is a better place for doubts and implementation issues (don't forget to provide your failing code).

**Comment by mangomkt** [comment]
One that works for me is this:

`window.addEventListener('click', function(e){
  if (document.getElementById('sidr-main').contains(e.target)){
    //console.log("Clicked in Box");
  } else {
    jQuery.sidr('close', 'sidr-main');
  }
});`
