### ISSUE TITLE
Change source URL from sidr

### ISSUE THREAD

**Issue by juju95** [artberri/sidr#120]
Hi,

First thanks for this great script working perfectly

Here is my case : 
- Click on a link on our site => Open right sidebar
- In the file loaded in the sidebar, if user is not identified, we open the login page in the sidebar in place of the original page.
- When the user validate the form and login is ok, we change the sidebar to the previous called page

I completed most of it, just a question, how to change dynamically the source URL when the sidebar is already loaded ? and can it be made directly from the file loaded in the sidebar ?

Thanks in advance

**Comment by artberri** [comment]
You need to update the content with AJAX by yourself.
