### ISSUE TITLE
Jquery UI Autocomplete Bug in Sidr

### ISSUE THREAD

**Issue by juju95** [artberri/sidr#121]
I'm trying to use Jquery Autocomplete in a Sidr Panel but can't make it work, when i enter letters in the input, i see the ajax request in console.log but now result list is shown under the input after receiving the result

If i put exactly the same code on a normal page, not in sidr, autocomplete is working perfectly.

Any idea where can be the problem ?

( No js error in log anyway )

thanks in advance

**Comment by cleiton-tavares** [comment]
I'm having the same problem, unfortunately and the z-index as you said, did not work with me, will this issue be resolved?

**Comment by cleiton-tavares** [comment]
I managed to solve using a method of jquery autocomplete "appendTo" and placed to give the append in a div within the Sidr

It was so

* autocomplete

```
$("#pagar_cliente").autocomplete({
  appendTo: "#nome_cliente",
  source: function(request, response){
   $.post("URL", {term:request.term, 'do': 'lstFinPessoas'}, function(data){
      response($.map(data, function(item) {
       return {label: item.valor,value: item.codigo}
    }))
   }, "json");
 }
});

```

* sidr

```
<div class="nome_cliente">
  <span class="forlinemax" id="nome_cliente">
    <h4>Digite o nome do  cliente *</h4>  
     <input id="pagar_cliente" class="campo text required grande  ui-autocomplete-input" validate="required:true " autocomplete="off" role="textbox" aria-autocomplete="list" aria-haspopup="true">
     <input type='hidden' name='cash[codigo_pessoa]' id="cash_codigo_pessoa" />
  </span>
</div>

```
