### ISSUE TITLE
Auto click when closing menu

### ISSUE THREAD

**Issue by Perrazoo** [artberri/sidr#124]
I'm developing a mobile adapted webpage.

I have a header element with 2 links (a menu from left and another from right) and in the middle I have my own logo (also a link to homepage).

On a mobile, left link opens menu fine, but when I click again to close the menu, in Nexus 5 my centered logo gets focus (like hover). Trying in another older device (Nexus One), the problem is bigger because the logo auto clicks itself when closing the left menu.

No issues on desktop...

Any ideas? Thanks.

**Comment by artberri** [comment]
Show your code when opening an issue.
