### ISSUE TITLE
Disable menu opening with right/left swipe touch events on certain div

### ISSUE THREAD

**Issue by Ashtj** [artberri/sidr#125]
I have an interactive map and whenever the map is browsed by zooming in and scrolling with swiping, the menus open. I would like to disable the right/left swipe touch events for the sidr menu or keep the sidr menus hidden when users swipe the #map.

**Comment by artberri** [comment]
Sidr do not implement swipe, so you it's not going to be solved here. Try to paste your code in stackoverflow.com
