### ISSUE TITLE
Toggle two sidr with one button

### ISSUE THREAD

**Issue by maulinpandya2006** [artberri/sidr#131]
Hi,

I have a requirement of load two sidr with one button. Mean to say we have only one button and with this we have to toggle two Sidr's. On first click one sidr will close and other will open, reversion on second click. Also on page load one will open other will close by default.

help me as soon as possible.
Thanks,

**Comment by artberri** [comment]
You need to do it by yourself with `$.sidr('close', 'sidr-main');` and  `$.sidr('open', 'sidr-main2');`
