### ISSUE TITLE
Sidr needs two click on link, before showing.

### ISSUE THREAD

**Issue by pierissimo** [artberri/sidr#133]
Anyone can duplicate this issue?

**Comment by conor909** [comment]
I just downloaded v1.2.1 and I'm getting a similar issue.

The first time I attempt to open the sidr it takes 2 clicks.  After that it seems to work fine.  Do I need to initialize it on page load / show?

**Comment by sameetandpotatoes** [comment]
I just encountered the same issue, and none of the solutions here helped me. I think the simplest solution is to trigger the first click programmatically as soon as the plugin is initialized in your javascript. Simply add `$('.switch').click();` after initializing sidr.

**Comment by artberri** [comment]
Please before reopning this issue give a jsfiddle, a codepen, a url or somewhere we can reproduce the error.
