### ISSUE TITLE
Hover and click effect not working properly

### ISSUE THREAD

**Issue by crippd** [artberri/sidr#143]
Hi
I'm using sidr in my project. I've done all the integration and tested it. The hover and click effect of menu item don't work properly, it shows some irregular behavior in desktop as well as mobile browsers.
Here is the link where you can see the issue live : http://crippd.com/live-testing-server/
follow the link and click on "Home" link on nav-bar.
Help me resolve the issue ASAP.

Thanks
Vikas

**Comment by artberri** [comment]
I'm late sorry.
