### ISSUE TITLE
1.1.1 Perfect. 1.2.1 Broken in android 

### ISSUE THREAD

**Issue by kiddac** [artberri/sidr#144]
Having used sidr(1.1.1) on a previous project and working fine on all devices tested, IE, Chrome, firefox, safai, opera, io6, iphone 4, android 2.3, android 4.2 I came across problems when I tried to use it for a second project.

The newest version 1.2.1 and also the sidr-master files just didn't work like the old one. Fine on the desktop, unusable on my Android (4.2.2).  

The problem is the side menu is used to link to anchor tags in my one page website. I therefore have the following code to close the sidr menu on a click.

 $(window).resize(function(){
   $.sidr('close', 'sidr-main');
 });
 
$(document).click(function () {
  $.sidr('close', 'sidr-main');
 });

Now the problem I was having is if I click on the menu icon, the sidr menu opens and then closes straight away. For some reason it is registering a click on the top item of my list. 

i.e if my top item is "about" it is closing the menu and jumping straight to the about section with out me clicking on anything.

After pulling my hair out for hours changing my code, disabling all other script calls etc etc, I decided to try the old version 1.1.1. And all is working perfectly again.

Therefore, is this something that has been modified in version 1.2.1 or is it an android bug that is auto selecting this top item.

**Comment by raphael-m** [comment]
I can confirm that removing the condition checking for `ontouchstart` solves the problem in Android. I did not see any side effects.

Instead of
```
if('ontouchstart' in document.documentElement) {
	$this.bind('touchstart', function(e) {
		var theEvent = e.originalEvent.touches[0];
		this.touched = e.timeStamp;
	});
	$this.bind('touchend', function(e) {
		var delta = Math.abs(e.timeStamp - this.touched);
		if(delta < 200) {
			e.preventDefault();
			methods.toggle(name);
		}
	});
}
else {
	$this.click(function(e) {
		e.preventDefault();
		methods.toggle(name);
	});
}
```
Use
```
$this.click(function(e) {
	e.preventDefault();
	methods.toggle(name);
});
```
What is the purpose of this condition?

**Comment by artberri** [comment]
Preparing a new version with a fix for this https://github.com/artberri/sidr/tree/reborn
