### ISSUE TITLE
Auto-Close Sidr on window.resize

### ISSUE THREAD

**Issue by Robdebert** [artberri/sidr#147]
If you open Sidr and then resize the browser (make it wider), the body still has it's inline-styles position:absolute, width, and so on.

Please add this to the plugin, so sidr is closed everytime, the browser-window is resized. This will avoid visual bugs.

window.onresize = function(){
		 jQuery.sidr('close', 'sidr-main'); // "sidr-main" should be replaced to something, that addresses all active Sidr-Containers.
	}

**Comment by artberri** [comment]
Add those things by yourself, there is no need to include it in the plugin
