### ISSUE TITLE
Sidr Selectors (null)

### ISSUE THREAD

**Issue by Robdebert** [artberri/sidr#148]
If an element does not exist, there is a string "null" in the sidr-bar.

Example:
$('#mainmenu_toggler').sidr({
		  name: 'sidr-main',
		  source: '#header #logo .custom, #top .moduletable.right'
		});	

if for some reason "#top .moduletable.right" does not exist, it should simply not get inserted to the sidr-bar.

**Comment by artberri** [comment]
Why? Why are you adding a non-existent element? use a callback instead.
