### ISSUE TITLE
Disable x and y coordinate scrolling of content

### ISSUE THREAD

**Issue by mensahf** [artberri/sidr#15]
I've successfully implemented this plugin but I'm having issues on mobile devices (iPhone/iPad)  where the content to the right of my left sidr panel can scroll in the x and y direction. This becomes an issue because the trigger button is easily lost. 

On Chrome/FF/Safari (desktop) I do no get this issue.

I tried setting overflow to hidden for my content wrapper but it does not work. Does anyone have any suggestions?

Thanks.

**Comment by cmathieu333** [comment]
For some reason using overflow: hidden and height: 100% on the body caused my sub navigation toggle animations within Sidr to break. The following did the trick for me though:

$('#right-menu').sidr({
  name: 'sidr',
  side: 'right',
  onOpen: function() { $('body').css({ 'position': 'fixed' }); }, // Prevents losing the close button on scroll
  onClose: function() { $('body').css({ 'position': 'static' }); } // Restores normal scrolling
});
