### ISSUE TITLE
Links not clickable on Samsungs Galaxy S3 native browser

### ISSUE THREAD

**Issue by Eternal-Infinity** [artberri/sidr#152]
Hi there,

first of all: thank you for this great plugin!!
This is just what I needed and it works perfectly for me.
Except for one thing...

I made a website responsive with sidr, the navigationbar works great in the browsers I tested...but I did not test with the native internet browser of my Samsung Galaxy S3, running Android 4.3.
The links of  the navigation-bar are not clickable in that browser.
Like there is some overlay or something.

Has anyone the same problem and/or any solution to this?

**Comment by artberri** [comment]
Is this still happening?
