### ISSUE TITLE
Issue with sidr disappearing in webkit.

### ISSUE THREAD

**Issue by robbieobbie** [artberri/sidr#159]
URL: http://auroracap.net

When clicking on the menu button in the top left in webkit browsers to open sidr and reveal the menu, sidr sometimes opens properly, while other times appears completely empty looking like a plain white box. If it does open properly, clicking on a link will turn sidr completely white.

Even stranger, once the error occurs, if the menu button is clicked to close sidr, and then is reopened, there are no issues.

It only seems to break once and then work from there on out.

Any ideas or suggestions would be GREATLY appreciated as I have been working on this for many hours now with no solutions. 

I should add that it works great in firefox if you would like to see it working properly.

![screen shot 2014-04-17 at 7 12 18 pm](https://cloud.githubusercontent.com/assets/7172633/2738045/f7e16a62-c685-11e3-9ab1-60d5403a3fed.png)

**Comment by bluedevil2k** [comment]
This issue doesn't look closed to me.  I've just installed the latest version (2.2.1), installed the jquery.sidr.js, got it wired up and working correctly on Firefox and Edge, and seen this same exact issue on WebKit based browsers.  @robbieobbie said he fixed it, but doesn't give any details on how it was fixed.  I'm not using leanmodal in my project.
