### ISSUE TITLE
collapses several seconds for Chrome

### ISSUE THREAD

**Issue by izcomaco** [artberri/sidr#167]
Hello, 

(Even if a text is amusing, please understand that it is unfamiliar into English.)

Sidr is arranged on left-hand side. 

Immediately after a screen changes, for several seconds, html for Sidr  is displayed on the upper left, and is normally displayed in several seconds.

Soon after a screen changed, for several seconds, html for Sidr(css is only a border property) is displayed on the left and is displayed normally several seconds later.

This problem occurs in Chrome.
Safari,firefox is fine.
Because IE did not support, I did not test it.

When I tested it with the html file which any data were not in, there was not a problem.

I converted it, and php file became in such a state when I made a server request.

**Comment by Teranode** [comment]
I'm experiencing this issue too

**Comment by artberri** [comment]
Can not understand this issue. Could you explain it better or give a URL example?
