### ISSUE TITLE
Closing Sidr disable scrolls

### ISSUE THREAD

**Issue by rowenseeker** [artberri/sidr#169]
So im using Sidr to create a navigation for a singlepage based on fullpage.js.

When im opening the left sidr and closing it, my scrollbar disappears and the site becomes static, except i can still jump to sections per navigation links in the sidr bar.

it seems like sidr is oberwritting the overflow option on the html tag in a weird way...

**Comment by artberri** [comment]
The only style that is being added to html tag is overflow-x, so it should not affect it. Give a jsfiddle sample please.
