### ISSUE TITLE
Slide fixed header

### ISSUE THREAD

**Issue by agrigg** [artberri/sidr#17]
I've got a fixed header that stays at the top of each page and when I use sidr it moves the rest of the pages, but not the fixed header. The css I'm using for the header is

.navbar-fixed-top
{
    position: fixed;
}

Is there a work-around or a way I could hook into the open and close events to alter the css while the menu is open?

**Comment by alexisletrotteur** [comment]
I've got issue with moving fixed header along with body on firefox 39.0. It stays at the same position. But once it get focus, it then moves into position. Anyone experiencing the same issue? Works in all other browsers.
