### ISSUE TITLE
Delay for Open and Close Sidr

### ISSUE THREAD

**Issue by juanjosezg** [artberri/sidr#177]
I know that we have the Speed option to set de durarion of opening and closing the sidr like this:

$('#simple-menu').sidr({
    side: 'left',
    speed: 5000   //Value is in milliseconds I believe. Adjust this for the duration of opening and closing. Default: 200.
});

but i want to set different values for every action for example: 
have.

Speed: 500 on opening and 200 on close how could be that possible?

**Comment by artberri** [comment]
It's not possible sorry.
