### ISSUE TITLE
Sidr doesn't work on some computers/browser

### ISSUE THREAD

**Issue by ianharris32** [artberri/sidr#178]
Really strange one.. I have people use a site I have used sidr on and the menu doesn't slide out. Thing is, on every computer I have tried it works, until today I experienced it not working. This was on google chrome as well. 
Since then I have changed the order of my js and css in the head tags to call the js first. Not sure if that solves it. Maybe I am missing something in the code... but I can't understand why it doesn't work on some computers, even with the same browser. 

the site is... thelangton.org.uk

Would appreciate the help asap please, I want to get this site finished. 

Cheers

**Comment by artberri** [comment]
Preparing a new version with a fix for this https://github.com/artberri/sidr/tree/reborn
