### ISSUE TITLE
S3 Android Ver#4.3 Native Browser Doen't Work With Floats

### ISSUE THREAD

**Issue by rooksstrife** [artberri/sidr#180]
I have seen this issue post all over and 0 fixes work.  I noticed that when I float the logo and the button to open the menu - it cause the button (when you press it) to open the menu for a sec, but go to the first link in the menu.  If you remove the float it works, but when you close it it goes to the logo link.  If you remove all float = 100% works.  Code:

HTML:
```
    <header class="clearfix">
    <div id="bwcc_logo"><a href="index.html"><img src="img/B_logo.jpg" alt="B"></a></div>
    <div id="menu_toggle"><a id="toggle" href="#sidr"><img src="img/drop_icon.jpg" alt="Toggle Menu Button" /></a></div>
	<div id="sidr"> 
		<ul>
			<li class="active"><a href="index.html">B Home</a></li>
			<li><a href="overview.html">Page</a></li>
		</ul>
	</div>
    </header>
```
CSS:
#bwcc_logo {
	float:left;
	max-height: 42px;
	max-width: 125px;
	padding: 10px 0;
	width: 100%;
	height:auto;
}
#menu_toggle {
	color: #fff;
	float: right;
	margin: 15px 25px 0 0;
	position:relative;
}
Plus the normal Sidr code.

It is as if the a href are not moving (floating).

**Comment by artberri** [comment]
Thanks @TheWebDevKev
