### ISSUE TITLE
sidr panel does not scroll on android 2.3

### ISSUE THREAD

**Issue by Shoekrates** [artberri/sidr#186]
Hi! 
sidr 1.11 works like a charm on nearly every device I have tested. Only android 2.3 browser gives me headaches. The sidr-content opens perfectly but as we have a longer vertical navigation the user has to scroll down. But only the barely visible body scrolls instead of the open sidr-content.

I tried several things:
 - played with overflow settings in sidr-main and sidr-inner
 - played with height-settings for above mentioned divs.
 - added overthrow.js from filament group

No resolution yet. Does anyone has another suggestion?
Sorry, can't give you a link because it's an intranet page.

*One mention regarding sidr version: We don't use sidr 1.21 because it was buggy for newer android browsers and iOS 5. There are some open issues here regarding this problem. Taking the older version as stated in these issues solved it.*

**Comment by artberri** [comment]
Sorry we will have a new version of sidr soon, but I'm not sure if will solve this issue. We will not support android 2.3 anymore.
