### ISSUE TITLE
Add option for displace to resize displaced element's width

### ISSUE THREAD

**Issue by fpayer** [artberri/sidr#187]
There should be a way to set a displaced element's width to shrink when sidr is opened. Doing so will fix issues with center-aligning things inside the displaced object.

Even your site(http://www.berriart.com/sidr/), opening sidr only pushes the body to the left or right. This triggers horizontal scrolling and does not allow the rest of the content on the page to be centered properly. 

I tried modifying the source to set the width properly in the transition, but it does a weird rubber-banding thing where it moves to one side with the left/right change and then the other direction with the width resize.

**Comment by raduluchian** [comment]
I am facing the exact same issue as described by @fpayer . Also tried to add some support for width adjustment but get the same behaviour as him. This is bad for websites that have a classic centered container.

**Comment by artberri** [comment]
Sorry this option will not be added, there are only two behaivours displace or not that you can set in options.
