### ISSUE TITLE
Sidr not opening on Google Chrome 36

### ISSUE THREAD

**Issue by Webtransformer** [artberri/sidr#193]
Sidr is working well on IPAD2, Android, Firefox and even Internet Explorer 8 but in Google Chrome v36 the content seems to be missing.

Here is a temporary project Link. The left top button is the link button for sidr.
http://2016.webtransformer.de/leistungen.

I am using the latest sidr version.

**Comment by mabasic** [comment]
For the love of God! It took me a lot of time to notice this.

If you have a touch screen clicking with the mouse on the toggle will not open the menu, but using your finger on it will open it.

**Comment by artberri** [comment]
Preparing a new version with a fix for this https://github.com/artberri/sidr/tree/reborn
