### ISSUE TITLE
Scrollbar issue

### ISSUE THREAD

**Issue by sama55** [artberri/sidr#196]
Thank you for your great script. Because I found tiny issue, I will report it.

Phenomenon:
Because style of HTML tag disappears when we set any other selector in "body" parameter, scroll bar may disappear on the page.

Solution:
https://github.com/artberri/sidr/blob/master/src/jquery.sidr.js (L164)
Before:
$('html').removeAttr('style');
After:
if($body.is('body'))  // Add one line
  $('html').removeAttr('style');

My site moved definitely with upper change, but there may be better solution.
Thank you.

**Comment by artberri** [comment]
Now it will remove only the previously added style
