### ISSUE TITLE
Sidr not closing by clicking of anchor link to same page

### ISSUE THREAD

**Issue by Dongapo** [artberri/sidr#199]
The sidr menu doesn't close if I click a link which points on the same page but to a different position (anchor link). If I click an anchor link which points to a new page then it works...
Probably it is not a bug.. but maybe I just do it wrong.
Any idea?

**Comment by madlenkaf** [comment]
Hello, I have the same problem. Please, do you have any idea to fix it? Thanks

**Comment by artberri** [comment]
You will need to do it by yourself

~~~ js
$( '.sidr li a' ).click(function () {
    $.sidr('close', 'sidr');
});
~~~
