### ISSUE TITLE
Slider not opening in iphone (haven't tested other mobile devices)

### ISSUE THREAD

**Issue by dstone1983** [artberri/sidr#201]
Hello,

Your slider works great so far in regular browsers in my responsive website.  It however doesn't seem to be working on the one mobile device I have tested on (iphone).  The site is incomplete and wanted to get the slider implemented early so I could work out any bugs.  I currently have the home page hosted here:

http://dustin-stone.com/D10/index.php

jquery call:

$('#simple-menu').sidr({
      name: 'sidr',
      side: 'right'
    });

button

<a id="simple-menu" class="box-shadow-menu" href="#sidr">Toggle menu</a>

Menu itself for mobile

<div id="sidr">
    <ul>
      <li>
        <form class="relative">
          <input type="text" name="search" placeholder="Search our products" />
          <div class="ico search"></div>
          <input type="submit" class="none" />
        </form>
      </li>
      <li><a href="">Home</a></li>
      <li><a href="">About Us</a></li>
      <li><a href="">Contact Us</a></li>
      <li><a href="">Track Order</a></li>
      <li><a href="">Shopping Cart</a></li>
      <li><a href="">Sign In</a></li>
      <li><a href="">Return Policy</a></li>
      <li><a href="">For Contractors</a></li>
      <li><a href="">Request Pricing</a></li>
    </ul>
  </div>

I appreciate any feedback as to what the issue might be.

**Comment by artberri** [comment]
Sorry for the late response, I will close this. Reopen it if you give a new example.
