### ISSUE TITLE
On iOS css sometimes sticks once closing

### ISSUE THREAD

**Issue by jrgleason** [artberri/sidr#202]
This happens very randomly, but I have a button that moves when the sidr slides out and reverts when closed. This seems to work great in chrome, however, in iOS7 (iPad) it has a tendancy to stick. Is there anyway around this? Sorry if this is a duplicate good news is on my devices everything else works great 
:-)

**Comment by artberri** [comment]
Please add a jsfiddle with a failing example, but if is random is going to be difficult.
