### ISSUE TITLE
I can drag body content

### ISSUE THREAD

**Issue by linuxjcq** [artberri/sidr#207]
Hi, 
    When I use sidr, everything goes well, except that: I open left menu bar, in the same time, the body'content in the right could be draggable in the left menu , how could I fix this?

best wishes!

**Comment by Blindmikey** [comment]
This worked for me:

js:
```
var scroll;

$('#mobile-nav-toggle').sidr({
    source: '#mobile-nav',
    side: 'right',
    onOpen: function() {
        scroll = $(window).scrollTop();
        $('body').css('margin-top', -1 * scroll);
        $('html, body').addClass('prevent-scroll');
    },
    onClose: function() {
        $('body').css('margin-top', 'auto');
        $('html, body').removeClass('prevent-scroll');
        $(window).scrollTop(scroll);
    }
});
```
css:
```
.prevent-scroll { position: fixed !important }
```

**Comment by artberri** [comment]
You can always place an overlay like in this example https://github.com/artberri/sidr/blob/master/examples/nodisplaced-menu-with-close-options.html
