### ISSUE TITLE
Unexpected gap when closed in Chrome with fixed position element

### ISSUE THREAD

**Issue by kidd001** [artberri/sidr#209]
This is how my site looks like:

https://s3-ap-southeast-2.amazonaws.com/uploads-au.hipchat.com/22527/565130/czuvDNXI51Pqp0v/upload.png

And I found the same issue on sidr's official site

https://s3-ap-southeast-2.amazonaws.com/uploads-au.hipchat.com/22527/565130/LnAnKT1cPAQLMCY/upload.png

Any solution for it?

**Comment by artberri** [comment]
Not happening to me, I need more info to try to help you.

**Comment by cptstarling** [comment]
I'm having the same issue, but Chrome's doing just fine. It's Safari (on desktop) that shows this behaviour.

I'm using a Sidr element which is sliding in from te right. When the page is loaded, everything looks fine, but when Sidr is triggered and closed again, it would leave a gap next to a `fixed` element in the site.

E.g.:
```
<div class="my-menu" style="position: fixed; top: 0;"> 
  <ul>
    <li>Home</li>
    <li>Contact</li>
    <li>Open Sidr</li>
  </ul>
</div>
```

When `left: 0` or `right: 0` is added as a style to my-meny this behaviour isn't occuring, but my-menu won't budge either when triggering Sidr.
