### ISSUE TITLE
Click using a touch enabled device doesn't work

### ISSUE THREAD

**Issue by techytuppers** [artberri/sidr#213]
Touch enabled laptop, but using a mouse. Clicking the toggle doesn't show the sidr menu as it's not detecting touch.

Windows 8. Chrome vs 37.

**Comment by dinitrol** [comment]
+1

**Comment by towfiqi** [comment]
+1

**Comment by master412160** [comment]
+1

**Comment by artberri** [comment]
Preparing a new version with a fix for this https://github.com/artberri/sidr/tree/reborn

**Comment by kujiy** [comment]
@artberri Thanks a lot for fixing it.

**Comment by artberri** [comment]
The new version is already out 
https://github.com/artberri/sidr/tree/v2.0.0
