### ISSUE TITLE
Suggestion: Have a Bare Bones CSS

### ISSUE THREAD

**Issue by jlabresh1** [artberri/sidr#216]
First of all, thanks for this tool, it is very useful and it helped me get a jump start on a slide out menu. After using this, I found it useful to create a bare bones css file so that sidr wont overwrite styles inside of the sidr sidebar when I used existing content. 

I use bower to grab these source files, it would be nice to have a barebones file in the repository so that if there is a core change to the structure, the barebones functionality would still continue to work.

If you need a bare bones css, I have one to use as a start if you like.

Thanks for your time.

-J-

**Comment by nsteiner** [comment]
I agree, I've made a quick SCSS version here: https://gist.github.com/nsteiner/f77f16e4aafde220cc77

**Comment by nsteiner** [comment]
Hooray - thanks @artberri 👏

**Comment by jlabresh1** [comment]
Thank you!
