### ISSUE TITLE
Handling elements with position:fixed

### ISSUE THREAD

**Issue by AlfredJKwack** [artberri/sidr#227]
Hi,

Sidr is unable to appropriately cater to elements with a css attribute like "position: fixed".
I've drawn up a [CodePen example](http://codepen.io/anon/pen/PwPWJm) covering a couple of use cases trying to animate either a discrete fixed element or the body along with a fixed element.

I'm hoping some of the cases can get resolved although I realize that this can get rather complicated. Unfortunately I'm not comfortable enough with the Sidr codebase to submit a patch for this.

**Comment by artberri** [comment]
You need to add different styles for elements inside sidr. I can not help you it's extremly edge case.
