### ISSUE TITLE
Sidr expanded menu stays open and the page doesn't restore

### ISSUE THREAD

**Issue by PagesByZ** [artberri/sidr#231]
I have implemented the Sidr menu in my website. When the page becomes small and the top sidr header is shown. I click on the menu icon in the header to show the menu which flies out from the left side. If I enlarged my browser to the desktop size while it is open, my website doesn't resize to normal width and the sidr fly out menu stays on the screen. I can show an example if needed.

How would I resolve it?

**Comment by sharathdaniel** [comment]
Any fix to this issue?

**Comment by d4nyll** [comment]
It sure would be nice if this was built into the 'core', but for now, you can simply check the `window` for the `resized` event, and close the slider programmatically.

```js
$( window ).resize(function() {
    // Optional - check the window size is above, say 1023px, for Desktop
    $.sidr('close', 'sidr-main');
});
```

(replace `sidr-main` with the name of your slider)

**Comment by artberri** [comment]
Thanks @d4nyll
