### ISSUE TITLE
Allow sidr to always be open

### ISSUE THREAD

**Issue by bjames105** [artberri/sidr#235]
In my current predicament, I'm using sidr in its intended purpose, to have a side menu.  However, I would like the links I put in sidr to be available if the width of the web browser is more than 1024 pixels, but I can't toggle sidr open and not have it cover something or push the page contents out the way without finagling of some sort.  Is there any way to toggle sidr open when the webpage is big enough to show my side links? Thanks!

**Comment by alokpant** [comment]
Why not create a sidebar for normal desktop use and only use sidr for medium and small devices?
