### ISSUE TITLE
Visible menu on Destop

### ISSUE THREAD

**Issue by whichrtmej** [artberri/sidr#237]
Hi,  I am new to all this.  When I add the plug in it works fine when view on desktop browser that is resized small but when I make my browser window large the slider menu and menu button disappear and I can't see my menu at all.  How do I get my menu to show up on a desktop screen.

Thanks whichrtmej

**Comment by pedroserapio** [comment]
The core idea of Sidr is to show a side Menu when the screen it's small and hide the side menu when the screen it's large. Sidr that the menu items from the original menu and display inside the new Sidr Menu, this mean:

Big Screen -> Show Original Menu -> Hide Sidr Menu
Small Screen -> Hide Original Menu -> Show Sidr Menu

This is possible with Media Query, and the results depend of where you put your display:block.. display:none

If you can show your code, it will be more easy to help you.

**Comment by whichrtmej** [comment]
Thanks.  I do understand that. 
Big Screen -> Show Original Menu -> Hide Sidr Menu -> Not Working
Small Screen -> Hide Original Menu - > Show Sidr Menu -> Working

Here is my code.

![screen shot 2015-01-24 at 9 13 32 am](https://cloud.githubusercontent.com/assets/1203166/5887796/bc3b7fe6-a3a9-11e4-8f8d-6564866c33db.png)

**Comment by pedroserapio** [comment]
Ok, following your CSS I see that your telling your browser to hide the Icon that give access to your menu when the screen it's smaller then 767px.
If your idea it's to keep the menu just set:
#mobile-header{
   display:block;
}

And delete the Media Query:

@media only screen and ...

**Comment by whichrtmej** [comment]
Ok, I did as you have suggested and the menu icon is always visible and I can access my menu all the time.  BUT

By reading my original post again, I did not state exactly what I was wanting clearly.  So I will try again.. Hopefully this will explain better.  

When someone is looking at my site, on a smart phone, I want the menu Icon to appear, as it does, and the user can click it and the menu slides in.  When they look at my site on a desktop or iPad I want the menu Icon to disappear and the horizontal menu to appear on the page.

If you go to the home page of the Sidr plugin, http://www.berriart.com/sidr/, and resize the page, make it smaller, you will see their horizontal menu disappear and the menu icon appear. Then when you make it larger the menu icon disappears and the horizontal menu appears.

Thanks whichrtmej

**Comment by pedroserapio** [comment]
#mobile-header{
	display:none;
}

.nav-bar{
	display:block;
}

@media only screen and (max-width: 767px){
	#mobile-header{
		display:block;
	}

	.nav-bar{
		display:none;
	}	
}

**Comment by whichrtmej** [comment]
When I tried this nothing happened.  I opened it in Google Chrome and "inspected Element"  it shows me the following.
![screen shot 2015-01-25 at 9 31 41 am](https://cloud.githubusercontent.com/assets/1203166/5891967/1bf67c8a-a475-11e4-8bd8-4e9a79b5a473.png)

When I uncheck the "display: none" in .sidr{ css.  The menu appear on the side like so.
![screen shot 2015-01-25 at 9 35 32 am](https://cloud.githubusercontent.com/assets/1203166/5891979/9b8530e0-a475-11e4-9506-c56184c4df17.png)

**Comment by alokpant** [comment]
it would have been alot easier to create a jsfiddle than copy paste the codes here. If this is already solved then please close this issue.

**Comment by artberri** [comment]
I will close this because I understand that is already solved. If not, try to create a jsfiddle instead of uploading a screenshot.

**Comment by markcanals** [comment]
#sidr { display: none; }
body.sidr-open #sidr > ul { display: block; }
@media only screen and (max-width: 1200px){
     #sidr { display: block; }
}
