### ISSUE TITLE
Hover Menü

### ISSUE THREAD

**Issue by der-phillip** [artberri/sidr#239]
Hello,

how can I make a Off Canvas Menü on hover, not on click like http://feedly.com?

**Comment by alokpant** [comment]
Feedly does not use Sidr. It uses simple css to achieve the functionality.
Feedly does not use sidr to achieve that functionality. It is simple css. 

http://codepen.io/gorkhali/pen/myoowx

I have tried the same using sidr.

http://codepen.io/gorkhali/pen/bNZZLz

Though I am not completely satisfied with it.

**Comment by artberri** [comment]
Yes you can add the option with JS

~~~ js
$('#whatever').hover(function () {
    $.sidr('close', 'sidr-main');
});
~~~
