### ISSUE TITLE
Windows Chrome V40.0.2214.94 m

### ISSUE THREAD

**Issue by avanriet** [artberri/sidr#240]
The sidr menu won't open on this specific version of Chrome and only happens on Windows (tested Windows 8.1), all other browser (FF, Safari, IE work like a charm).
The according classes aren't added on the body like on the other browsers same as the needed css. 

Does anyone know how to fix this or has the same issue?

Thanks in advance.

**Comment by bobreichard** [comment]
Yes, experiencing the same issue.

**Comment by rqbukhari** [comment]
I'm also experiencing the same issue. But sometime it works on Chrome as well. Very strange behavior. I can't see any error.

**Comment by promoinvideo** [comment]
Maybe I've got the problem: is it possible that you use a PC with both mouse and touchscreen? I  had experienced the same issue and afer some investigation I realize that CHROME needs the CLICK event. I had modified the main js by adding the click event
                    $this.click(function (e) {
                        e.preventDefault();
                        methods.toggle(name);
                    });
after the line 316. I hope you can find this patch useful to solve your problem.

**Comment by pabeln** [comment]
Have the exact same issue as promoinvideo but using Chrome Version 42.0.2311.135 m (64-bit). 

On PC with dual monitors and one is a touchscreen, the other is not and the mouse click event is ignored but the touch event is not. Also, if I go into Chrome dev tools and emulate a device and activate "Emulate touch screen", the touch events trigger Sidr. 

I'll try to figure this out and post back shortly.

**Comment by master412160** [comment]
Hopefully the author sees this and updates the code.

**Comment by pabeln** [comment]
The fix is pretty easy.

Change this: (starting on line 289)
```javascript
if('ontouchstart' in document.documentElement) {
	$this.bind('touchstart', function(e) {
		var theEvent = e.originalEvent.touches[0];
		this.touched = e.timeStamp;
	});
	$this.bind('touchend', function(e) {
		var delta = Math.abs(e.timeStamp - this.touched);
		if(delta < 200) {
			e.preventDefault();
			methods.toggle(name);
		}
	});
}
else {
	$this.click(function(e) {
		e.preventDefault();
		methods.toggle(name);
	});
}
```

To This:
```javascript
$this.bind('touchstart', function(e) {
	var theEvent = e.originalEvent.touches[0];
	this.touched = e.timeStamp;
});
$this.bind('touchend', function(e) {
	var delta = Math.abs(e.timeStamp - this.touched);
	if(delta < 200) {
		e.preventDefault();
		methods.toggle(name);
	}
});
$this.bind('click', function(e) {
	e.preventDefault();
	methods.toggle(name);
});
```

By removing the "ontouchstart" check I could bind both a click and a touch event to the element. 

Keep in mind I only tested this in Chrome both emulation mode and not. Hope this helps others.

**Comment by master412160** [comment]
@pabeln in what file do I apply this fix? jquery.sidr.min.js? Because that doesn't have (even when I use a unminify tool) a line 289.

**Comment by pabeln** [comment]
@master412160 I used the un-minified code here: 
https://github.com/artberri/sidr/blob/master/src/jquery.sidr.js

**Comment by master412160** [comment]
Thanks, got it.

**Comment by artberri** [comment]
Preparing a new version with a fix for this https://github.com/artberri/sidr/tree/reborn
