### ISSUE TITLE
Can I use a Backbone / Marionette LayoutView as source callback somehow? 

### ISSUE THREAD

**Issue by conor909** [artberri/sidr#241]
I'm trying to do somehting like this in the source callback:

    this.ui.addBusinessBtn.sidr({
      name: "MyForm", 
      speed: 200, 
      side: "left",
      source: function() {
        var content = new App.MyView.Layout();
        return content;
      },
      renaming: true,
      displace: false,
      body: ".main-region"
    });

and in my view file would be:

    Divesite.module("MyView", function(MyView, App, Backbone, Marionette, $, _){
        MyView.Layout = Marionette.LayoutView.extend({
            template: "/url-to-template.html"    /*   this would be the source path to the html  */
            className: "add-user-form",

            ui: {
                submitBtn: ".submit-btn"
            },

            events: {
                "click @ui.submitBtn": "addUser"
            },
 
            onShow: function() {
                this.addUser();
            },

            addUser: function() {
                // add user function
            }   
        });

    });

**Comment by artberri** [comment]
I'm not a Marionette user sorry, it should be possible but I can not help you, try stackoverflow instead.
