### ISSUE TITLE
Close on body click

### ISSUE THREAD

**Issue by Gabee8** [artberri/sidr#247]
Hello!
How to close left menu on click body or div id?
Thanks answer.

**Comment by 1012042** [comment]
Yes!, this my issue, can you help me?

**Comment by alokpant** [comment]
http://jsfiddle.net/mfnRK/93/

$(document).on("click", function () {
     $.sidr('close', 'respNav');
 });

**Comment by Gabee8** [comment]
Thanks!

**Comment by alokpant** [comment]
@Gabee8 no problem. If that worked for you then please close the issue.
