### ISSUE TITLE
Android WebKit Browser issue

### ISSUE THREAD

**Issue by miasanbm** [artberri/sidr#249]
I am facing an issue with the current #sidr menu code when I try to run my app in older version of Android Webkit browser. The menu works great in Android chrome browser and recent versions of Android WebKit browser. However little older version of Android Webkit browser the menu is not working. If I click on the menu in older WebKit browser then the menu slides/opens but then it slides/closes automatically within fraction of second. Therefore the menu almost is unusable.

**Comment by martinmacke** [comment]
Same here.

**Comment by jedsadha** [comment]
For support old version Android , I solve problems by remove "touch event" and just use only "click event".  (*between  line 289 to line 307)

**Comment by artberri** [comment]
Preparing a new version with a fix for this https://github.com/artberri/sidr/tree/reborn
