### ISSUE TITLE
Hello all,

### ISSUE THREAD

**Issue by 1012042** [artberri/sidr#251]
Please, My proplem is add new div or html code in sidr menu to create sub menu drop down.
EX: http://totaltheme.wpengine.com/base/
Can you help me.
Many thanks!

**Comment by alokpant** [comment]
Is there way to add sub menu beforehand? Else you can simple do it like this:

http://codepen.io/gorkhali/pen/ogVmdj

**Comment by artberri** [comment]
Thanks @alokpant
