### ISSUE TITLE
Scroll overflow problem

### ISSUE THREAD

**Issue by nikmauro** [artberri/sidr#253]
When insert big list in sidr menu the scroll not working well. Here the screenshoat 

![img sidebar menu problem](http://cdn.cdl.gr/upload/uploads/04-2015/1428045299_1787398a7e34f3016d93dc5903099351.png)

**Comment by jackdpeterson** [comment]
@nikmauro Are you experiencing this on the newest iOS or in another browser? This issue has been seen on iOS latest specifically (at least on some sites I work with). I'm not sure about elsewhere, but if so, then +1 to requesting that this issue be resolved or a workaround identified.

**Comment by ultraloveninja** [comment]
This maybe attributed to the overflow-y smooth scrolling on iOS: https://css-tricks.com/snippets/css/momentum-scrolling-on-ios-overflow-elements/

I've tested this out on my iPhone 5s with a site that we are using the `sidr.dark.css` file and that seems to resolve the glitchy scroll issue.

But in-regards to this particular issue, I'm not 100% sure since I don't know any of the details for the site issue at hand as @jackdpeterson mentioned.

**Comment by BWPanda** [comment]
I'm experiencing this exact same issue in Android 2.3.6's default browser with http://panda.id.au. Seems possibly related to #186...

**Comment by artberri** [comment]
Do you have set properly the viewport to not scale?

<meta name="viewport" content="width=device-width,minimum-scale=1">

**Comment by BWPanda** [comment]
I have this in the header of my website: <code><meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1" /></code>
Is that what you mean?

**Comment by artberri** [comment]
Hi @BWPanda 

I've opened your site http://panda.id.au/ and I see this viewport in the header:

~~~ html
<meta name="viewport" content="width=device-width">
~~~

Could you try this?

~~~ html
<meta name="viewport" content="width=device-width,initial-scale=1,minimum-scale=1">
~~~

You need to set your minimum scale AFAIK.

**Comment by BWPanda** [comment]
I have that already (see just under opening head tag). Looks like I also have the shorter one further down, not sure how that happened...

**Comment by artberri** [comment]
Uhm... I think that we are not seeing the same code, look at this screenshoot that I've taken from the above url, there is only one viewport meta and has not a minimum-scale:

[![SourceCode screenshoot](http://s24.postimg.org/quwm0oa51/Screenshot_from_2016_01_11_00_30_18.png)](http://s24.postimg.org/quwm0oa51/Screenshot_from_2016_01_11_00_30_18.png)

**Comment by BWPanda** [comment]
Hmmm, ok. Thanks for that. The CMS must be showing different things for different users or something...

In any case, I've added <code>initial-scale=1, minimum-scale=1</code> to the tag that does display for you so you should be able to see that now. However it doesn't appear to have made a difference to the display of the menu on my phone (still gets cut off at the bottom).

**Comment by artberri** [comment]
Well, now I'm seeing the menu properly on your web:

[![screenshoot](https://dl2.pushbulletusercontent.com/Lgkq1nhMkJBd3rhDB2V1K0xhnOob5Ogw/Screenshot_2016-01-11-10-09-31.png)](https://dl2.pushbulletusercontent.com/Lgkq1nhMkJBd3rhDB2V1K0xhnOob5Ogw/Screenshot_2016-01-11-10-09-31.png)

I haven't an Android 2.3 device to make the test, could you put an screenshoot to take a look to the problem? I'm not supporting old Android versions, but if is an easy fix I could try.

**Comment by BWPanda** [comment]
Here's my screenshot of the problem:
![sc20160112-080629](https://cloud.githubusercontent.com/assets/2385329/12247352/c45cd3ae-b907-11e5-8429-b637f8518fa5.png)

**Comment by Fatimah-Abdrabu** [comment]
I have faced the same problem using Sidr v1.2.1 but only when I set the menu side to the left!!!
So, setting the menu to the right solved my problem (and why? ofcourse I don't know ^^).

**Comment by artberri** [comment]
Sorry, try using last version.
