### ISSUE TITLE
Problem's with Responsive menu in RTL mode

### ISSUE THREAD

**Issue by Marshalsy** [artberri/sidr#254]
Hi!
Sidr is very nice menu for responsive theme on sites with LTR languages.
But i have problem  with site RTL language (hebrew).
Submenus in this menu located on the contrary, last submenu in first place and first submenu in end of list.

**Comment by artberri** [comment]
Could you give us some code example here, with a codepen or jsfiddle, or a link?

**Comment by artberri** [comment]
I'll close this issue until you give me more info.

I've tried RTL and I haven't seen any issue, sorry.

You can open it if you give us more info about your issue.
