### ISSUE TITLE
.sidr class with two positions

### ISSUE THREAD

**Issue by ultraloveninja** [artberri/sidr#256]
Not sure what the overall purpose is of this, but I was look into the `jquery.sidr.dark.css` file and I noticed that there are two positions declared within the `.sidr` class:

    .sidr {
     display: none;
     position: absolute;
     position: fixed;
     ...
    }

Wasn't sure if this is something that needs to be declared due to jQuery invoking something after menu is triggered, but seems like it might cause some conflicts down the line in other browsers. I noticed that in Chrome, that it totally ignores the `position: absolute` all the time. So I'm just not sure if it's needed or not.

**Comment by Teranode** [comment]
it's best to keep the fixed one, the absolute position has a bug where it would stay in ints exact position where a black bar would appear because of the right positioning.

**Comment by artberri** [comment]
It was for adding fallback to old mobile browsers that didn't support fixed, now has been removed for next version:

https://github.com/artberri/sidr
