### ISSUE TITLE
Problems embeding iFrames or other Scripts in Sidr

### ISSUE THREAD

**Issue by BeBo007** [artberri/sidr#257]
Hi there,

i love the simple implementation an usage of sidr, but the title says it: i have problems embed iFrames (some are not showing at all - like youtube - an others losing their functionality and layout) or other functions based on javascrip/jquery.
I simply don't get it. Can anybody help me to embed a iframe or another script?
This would stop me hitting my head on my keyboard... ;)

Thanx!
Be

**Comment by artberri** [comment]
Could you give us more info?
