### ISSUE TITLE
To Swipe the menu on android it works but not perfectly somehow

### ISSUE THREAD

**Issue by master412160** [artberri/sidr#258]
I copied your code and got no errors to show for it in google chrome but it doesn't work everywhere I scroll and the menu doesn't do full height in my device screen.

http://phpbb.miscy.net/index.php

Do you know why that is?

I haven't applied any custom css of my own to the menu but the menu that you can toggle on desktop works well without any css I add. It shows full height of the screen.

So why doesn't the swipe menu work the same way on my android device?

**Comment by artberri** [comment]
I see that your are not using it anymore, sorry for the late response.
