### ISSUE TITLE
font awesome icons overwritten

### ISSUE THREAD

**Issue by andersdn11** [artberri/sidr#259]
the icon classes will be prefixed with: sidr-class 

normal: class="fa fa-cube"

with sidre: class="sidr-class-fa sidr-class-fa-cube"

So the icons won't render.

**Comment by cedricblondeau** [comment]
To avoid this behavior, you can set the value of the option 'renaming' as false (http://www.berriart.com/sidr/#documentation).

**Comment by wpexplorer** [comment]
Or just add some javascript to rename them back onOpen...This way you can still rename everything else:

```
$( 'a.wpex-toggle-mobile-menu' ).sidr( {
    name     : 'wpex-sidr-menu',
    speed    : parseInt( wpexLocalize.sidrSpeed ),
    source   : wpexLocalize.sidrSource,
    side     : wpexLocalize.sidrSide,
    displace : wpexLocalize.sidrDisplace,
    renaming : true,
    onOpen: function( name ) {

        // Hide if wrap clicked
        $( '#wrap' ).click( function() {
            $.sidr( 'close', 'wpex-sidr-menu' );
        });

        // Re-add correct font Icons
        $( "#wpex-sidr-menu [class*='sidr-class-fa']" ).attr( 'class',
            function( i, c ) {
            c = c.replace( 'sidr-class-fa', 'fa');
            c = c.replace( 'sidr-class-fa-', 'fa-');
            return c;
        } );

    },
    onClose: function( name ) {

        // Nothing yet

    }

} );
```

Not sure how efficient the code and if there is a better way, but it works.

**Comment by artberri** [comment]
I recommend you to use the renaming option.

**Comment by wpexplorer** [comment]
If you use the renaming option though it prevents renaming for everything, using javascript as mentioned above still allows you to rename all other classes and ID's.

**Comment by artberri** [comment]
@wpexplorer yes, you are right. Your proposal is totally fine.

There is a pull request proposal to filter whick classes/ids are going to be renamed and I will valorate if it should go with the core.

**Comment by wpexplorer** [comment]
Great!

I love seeing this repository active again! I have made some tweaks on my own as well but never submitted pull requests because I thought the repo was "dead" maybe I'll start submitting some ;)
