### ISSUE TITLE
Sidr Menu Won't Display

### ISSUE THREAD

**Issue by markivee** [artberri/sidr#260]
Attached is my code. Simply put I'm attempting to use sidr but it doesnt want to display the menu on toggle. If I manually remove the display:none; tag from the .sidr it displays however doesnt allow for toggling, since it covers the toggle. 

Any help is appreciated. Thanks.

<html>
    
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
            <title>One Heart World-Wide</title>
        <meta name="description" content="One Heart World-Wide">
        <link href='http://fonts.googleapis.com/css?family=Montserrat:400,700' rel='stylesheet' type='text/css'>
        <link href='http://fonts.googleapis.com/css?family=Raleway:200,300,400,500,600,700' rel='stylesheet' type='text/css'>
        <link href="stylesheets/styles.css" rel="stylesheet">
        <link href="css/bootstrap.css" rel="stylesheet">
        <link href="stylesheets/jquery.sidr.dark.css" rel="stylesheet" type="text/css">
        <link href="css/bootstrap-theme.min.css" rel="stylesheet" type="text/css">
        
    
    <script src="/js/jquery-1.11.1.min.js"></script>

        <script>
                    $(document).ready(function() {
                    $('#simple-menu').sidr();
                    });
                </script>
        
    </head>
    <body>
        
        <a id="simple_menu" href="#sidr">
                 <div style="left:0px; position:absolute;">
                    <span class="menu">MENU</span>
                    <span class="menu"><img src="images/menu_bars.png"/></span>
                 </div>
                </a>
               
               <div class="sidr">
                
                
                    
                     <ul>
                        <li><a href="#">Home</a></li>
                        <li><a href="#">About Us</a></li>
                        <li><a href="#">Programs</a></li>
                        <li><a href="#">Donate</a></li>
                        <li><a href="#">Join Us</a></li>
                        <li><a href="#">News &amp; Media</a></li>
                        <li><a href="#">Contact Us</a></li>
                    </ul> 
                    
                </div>
        
        <div class="row header">
        
            <div class="col-xs-1">
                
            </div>
            <div class="col-xs-1">
                <a href="#"><img src="images/header_logo.png"></a>
            </div>
            <div class="col-sm-3">
                <span class="tagline">WE DELIVER. WE PROMISE.</span>
            </div>
            <div class="col-sm-4">
                    <a href="#"><span id="topnav">WHAT WE DO</span></a>
                    <a href="#"><span id="topnav">WHO WE ARE</span></a>
                    <a href="#"><span id="topnav">OUR RESULTS</span></a>
                    <a href="#"><span id="topnav">BLOG</span></a>
            </div>
             <div class="col-sm-2">
                    <a href="#"><span class="donate_button"><img src="images/donate_image.png" style="width:auto;"></span></a>
            </div>
            <div class="col-sm-1 fr">
                    <a href="#"><span class="join_button"><img src="images/join_image.png"></span></a>
            </div>
           
        </div>
            
        <div class="row color_bar"></div>  

    
    <script src="/js/jquery.sidr.min.js"></script>
        
    </body>
</html>

**Comment by ndmughal** [comment]
just past this code after <script src="/js/jquery.sidr.min.js"></script>

           <script>
                $(document).ready(function() {
                $('#simple-menu').sidr();
                });
            </script>

**Comment by artberri** [comment]
Thanks @ndmughal
