### ISSUE TITLE
Can not get Close button inside the sidr menu to work

### ISSUE THREAD

**Issue by srikat** [artberri/sidr#261]
URL: http://dev-altitude-pro-sidr.pantheon.io/

I have placed a 'Close Menu' button using the following HTML:

`<button id="close-menu">Close Menu</button>`

The relevant JS is:

```
jQuery(document).ready(function($) {
	$('#close-menu').click(function() {
		// Close
		$.sidr('close', 'sidr-nav-primary');
	});
});
```
Nothing happens when the close button is clicked.

Any idea?

**Comment by benhuson** [comment]
I notice you have this working now on that site.
How did you fix it?

**Comment by dev-guzior** [comment]
Hi, can you write how you made this with wordpress? :)

**Comment by artberri** [comment]
Here you have an example doing that:

https://github.com/artberri/sidr/tree/master/examples
