### ISSUE TITLE
The content of <li> in <div id="sidr> appear when page loading 

### ISSUE THREAD

**Issue by jasperck** [artberri/sidr#262]
Hi, this is first time I used `Sidr` in one of my projects,
although it works fine for almost everything,
one problem is when the new page was selected and loading,
the list content of the `<li>` will appear on the page first and then hide,
is there any solution I just miss? or anyone met same problem?
thanks!

**Comment by master412160** [comment]
How did you solve it?

**Comment by jasperck** [comment]
Hi, I just leaved the link of <a> at it's position, moved the <ul>...</ul> stuff to the bottom of the body,
and thus work for me. It's kind of dumb way. So if there is any better solution please tell me.
