### ISSUE TITLE
Sidr removes background image when menu closes

### ISSUE THREAD

**Issue by johnpanz** [artberri/sidr#263]
Has anyone had this issue before? I tried remove all styling from the CSS but don't know javascript so can't dig around in there.

Is this a common issue, or should I start looking for a new mobile menu plugin?

**Comment by artberri** [comment]
Give us some code and probably we can help you, this is not usual.

**Comment by DerExilant** [comment]
Hi,
I also have a similar problem. First sidr removes the background image and it  most times reappears when the sidebar get's closed. I've tried defining the background image for the html tag and also for the body tag.

The actual css code is:

html
	background-image: url('images/gelaenderbg.jpg')
	background-position: top center
	background-size: 100% 100%
	background-repeat: no-repeat

**Comment by artberri** [comment]
Try to follow this on #291
