### ISSUE TITLE
onClose should be called inside animation

### ISSUE THREAD

**Issue by rafaelsierra** [artberri/sidr#264]
Since sidr uses animation to close the menu, shouldn't `onClose` be called within the callback function of `.animate()`?

This way the function will be called only after the menu was really closed.

https://github.com/artberri/sidr/blob/master/src/jquery.sidr.js#L175

**Comment by Teranode** [comment]
This project hasnt been updated in 2 years >_>

**Comment by artberri** [comment]
For that the only way right now is to programatically close the menu and pass a callback not to use the onClose option:

jQuery.sidr( [method] [, name] [, complete] )

$.sidr( 'close', 'sidr', yourcallback )
