### ISSUE TITLE
Sidr not pushing navbar-fixed-buttom

### ISSUE THREAD

**Issue by donmyhl** [artberri/sidr#269]
hi 
I have a Sidr menu implemented inside a angularJs app with SPA. When i open sidr menu it does not push the navbar to the right like the other content.

Anybody who can help with a solution?

**Comment by donuan** [comment]
I have the oppsite problem. I want to keep my nav menu from sliding. How are you keeping it in position?

**Comment by donmyhl** [comment]
¨Do you have some code i can see? maybee the bav-bar and your sidr menu code. Maybee I can see what we doo differently.

**Comment by donuan** [comment]
I managed to keep it put now with the attribute:
position: fixed;
while before it was:
position: absolute; (which acted the same except that it was being pushed by the sidr menu)

try it maybe?

**Comment by donmyhl** [comment]
Did you put that directly on your html element or in css?

**Comment by donuan** [comment]
In the css (but both should work).

**Comment by artberri** [comment]
Seems that this is solved, but seems also that is regarding your own CSS. Please add some code here if you still need help.
