### ISSUE TITLE
Is there a way to close menu by clicking to menu item?

### ISSUE THREAD

**Issue by dare023** [artberri/sidr#271]
Hi, 
Is there a way to close menu by clicking to menu item?
Thank you  in advance.

**Comment by MandyGrimm** [comment]
Hi, you can use ul a.click and inside the click function sidr('close', 'sidr'), so it'll close the menu after the menu item is clicked.

$('ul a').click(function() {
		$.sidr('close', 'sidr');
});
I hope it works for you! =)

**Comment by dare023** [comment]
Yes, it does.
Somehow did not managed to it get from docs.
Thank you a lot!

**Comment by jentanbernardus** [comment]
Hi @dare023, optionally.. you could also use this code to close Sidr menu if clicked anywhere in the body but not the links.
     
    $(document).bind("click", function () {
         $.sidr('close', 'sidr');
    });

**Comment by dare023** [comment]
Already figured it out when got first sample of code.
But thank you for help, it is useful, of course.
Again, may be good to update documentation with this, as I failed to find such examples there.

**Comment by jentanbernardus** [comment]
Cool, no problem. +1 for updating the documentation, it indeed could be better. Maybe a pull request could help ;)





---

**Comment by artberri** [comment]
Will be added soon in a new section in documentation called 'cookbook'.
