### ISSUE TITLE
Not displaying correctly on mobile

### ISSUE THREAD

**Issue by celsoft** [artberri/sidr#274]
Hi. Not displaying correctly on mobile.
Browser: google chrome.
How to fix it?
This happens when you scroll down.
![screenshot_2015-09-10-02-53-03](https://cloud.githubusercontent.com/assets/5567863/9770872/32a39cd2-573b-11e5-8661-0e3fada98c8b.png)

**Comment by artberri** [comment]
Please give me the URL or some code to check and try to help you, but seems that the issue is not sidr related.
