### ISSUE TITLE
Issue on some Mobile Phones - sidr only opening halfway

### ISSUE THREAD

**Issue by MB721** [artberri/sidr#275]
I'm currently using two instances on a website, both coming from the right.  This is my first request so not sure if there is anything else to provide to help figure out the issue.

The issue is on some mobile phones. I have an iPhone 6 and it works perfectly for me. My friend has an iPhone 6+ and when he opens on certain pages the sidr doesn't open all the way. However, the navigation buttons push to the correct position, so I'm not sure why the sidr isn't completely open. Here are two screenshots, one is my iPhone 6, the other is the 6+.  I also checked on a Google Nexus phone and it had the half-open issue as well (using Chrome)

![img_6276](https://cloud.githubusercontent.com/assets/14249012/9831759/93104ca8-5931-11e5-8f99-e8f1bd9b0d1c.PNG)

![img_0039](https://cloud.githubusercontent.com/assets/14249012/9831732/340d5c42-5930-11e5-8eab-1d486c7a1a58.PNG)

Here is my code: 

```
	$(document).ready(function() {
		$('#responsive-menu-button').sidr({
			name: 'sidr-main',
			side: 'right',
			source: '#main-nav',
			body: '.mobile-nav',
			speed:'0'
		});
		
		$('#shownotes-menu-button').sidr({
			name: 'sidr-shownotes',
			side: 'right',
			source: '#shownotes',
			body: '.mobile-nav',
			speed:'0'
		});
	});
```

.sidr {
    background: black none repeat scroll 0 0;
    color: #fff;
    display: none;
    height: 100%;
    overflow-y: auto;
    position: fixed;
    top: 0;
    width: 260px;
    z-index: 999999;
}
.sidr .sidr-inner {
    background: #000000 none repeat scroll 0 0;
    padding: 0;
}
.sidr .sidr-inner > p {
    margin-left: 15px;
    margin-right: 15px;
}
.sidr.right {
    left: auto;
    right: -260px;
}
.sidr.left {
    left: -260px;
    right: auto;
}
.sidr h1, .sidr h2, .sidr h3, .sidr h4, .sidr h5, .sidr h6 {
    margin: 0 0 5px;
    padding: 0 15px;
}
.sidr p {
    font-size: 13px;
    margin: 0 0 12px;
}
.sidr p a {
    color: rgba(255, 255, 255, 0.9);
}
.sidr > p {
    margin-left: 15px;
    margin-right: 15px;
}
.sidr ul {
    display: block;
    margin: 0;
    padding: 0;
}
.sidr ul li {
    border-bottom: 1px solid #666666;
    display: block;
    line-height: 40px;
    margin: 0;
}
.sidr ul li a, .sidr ul li span {
    color: white;
    display: block;
    padding: 0 15px;
    text-decoration: none;
}
.sidr ul li ul {
    border-bottom: medium none;
    margin: 0;
}
.sidr ul li ul li {
    font-size: 13px;
    line-height: 40px;
}
.sidr ul li ul li:last-child {
    border-bottom: medium none;
}
.sidr ul li ul li:hover, .sidr ul li ul li.active, .sidr ul li ul li.sidr-class-active {
    border-top: medium none;
    line-height: 41px;
}
.sidr ul li ul li:hover > a, .sidr ul li ul li:hover > span, .sidr ul li ul li.active > a, .sidr ul li ul li.active > span, .sidr ul li ul li.sidr-class-active > a, .sidr ul li ul li.sidr-class-active > span {
    box-shadow: 0 0 15px 3px #222222 inset;
}
.sidr ul li ul li a, .sidr ul li ul li span {
    color: rgba(255, 255, 255, 0.8);
    padding-left: 30px;
}
.sidr form {
    margin: 0 15px;
}
.sidr label {
    font-size: 13px;
}
.sidr input[type="text"], .sidr input[type="password"], .sidr input[type="date"], .sidr input[type="datetime"], .sidr input[type="email"], .sidr input[type="number"], .sidr input[type="search"], .sidr input[type="tel"], .sidr input[type="time"], .sidr input[type="url"], .sidr textarea, .sidr select {
    background: rgba(0, 0, 0, 0.1) none repeat scroll 0 0;
    border: medium none;
    border-radius: 2px;
    box-sizing: border-box;
    clear: both;
    color: rgba(255, 255, 255, 0.6);
    display: block;
    font-size: 12px;
    margin: 0 0 10px;
    padding: 5px;
    width: 100%;
}
.sidr input[type="checkbox"] {
    clear: none;
    display: inline;
    width: auto;
}
.sidr input[type="button"], .sidr input[type="submit"] {
    background: white none repeat scroll 0 0;
    color: #333;
}
.sidr input[type="button"]:hover, .sidr input[type="submit"]:hover {
    background: rgba(255, 255, 255, 0.9) none repeat scroll 0 0;
}
.sidr .sidr-class-nav {
    color: #fff;
    font-family: "GothamLight",Helvetica,sans-serif;
    font-size: 1em;
    font-weight: bold;
    letter-spacing: 1px;
    line-height: 1.5em;
    text-transform: uppercase;
}

**Comment by artberri** [comment]
This is because the sidr menu has a fixed with of 260px on CSS and you are seeing it in a bigger display.

You can override it in your own CSS to adapt it to your needs, for example:

~~~ css
.sidr {
    width: 80%;
}

.sidr.right {
    right: -80%;
}

.sidr.left {
    left: -80%;
}
~~~
