### ISSUE TITLE
Sidr only allowing one nav element with child pages

### ISSUE THREAD

**Issue by robertblackmon** [artberri/sidr#277]
I'm extremely non-technical so apologize in advance...but the implementation of sidr I am working with will only allow proper function of one nav element that includes child pages. Subsequent elements with child pages don't display properly and auto-load the parent page.

Any help appreciated.

**Comment by artberri** [comment]
I need to see a bit of code to help you. Could you give me the page URL or paste some code?

**Comment by artberri** [comment]
I'll close this issue, give me more info and reopen it if you want.
