### ISSUE TITLE
Is this a dead project?

### ISSUE THREAD

**Issue by theMikeD** [artberri/sidr#278]
No updates in 2 years. Has this been abandoned?

**Comment by bradbamford** [comment]
Sure looks like it. I just came across this project and it looked promising for an off page mobile menu.

**Comment by matdave** [comment]
Still works! Lots of cool stuff could be added though, just need someone to pick it back up.

**Comment by artberri** [comment]
Well, it was death. My fault :( sorry.

But now I'm back again trying to reborn it: https://github.com/artberri/sidr/tree/reborn

Thank you for your interest.
