### ISSUE TITLE
To close the menu when the menu is open, please add a css object that covers the remaining screen

### ISSUE THREAD

**Issue by Eskarina** [artberri/sidr#28]
The idea is to fire the menu in his button, that's OK. But from an usability standpoint, a CSS object should be integrated, so when the menu is opened, a click in the remaining screen will close it.

As seen here:
https://github.com/NicholasRBowers/CSS-Slider-Menu

Please, I don't know how to add this via jquery. This is a very nice improvement.

**Comment by artberri** [comment]
You can try the overlay thing shown in this example 

https://github.com/artberri/sidr/blob/master/examples/nodisplaced-menu-with-close-options.html
