### ISSUE TITLE
Close menu when tapping anywhere on the screen

### ISSUE THREAD

**Issue by Gela** [artberri/sidr#280]
I need to change this menu so that the toggle menu can be closed by tapping anywhere on the screen and not just the toggle. I tried adding the code below suggested in #111  to my page within script tags but it didn't work.
```js
            //Closes the menu by tapping anywhere and not just the toggle
            $("html").on("click",function(e) { $.sidr('close'); }); 
```
Any idea what I'm doing wrong?

**Comment by jamesbradleyakers** [comment]
You need to state the element name and use stopPropogation so it ignores clicks in your menu.
```javascript
$("html").on("click",function(e) { $.sidr('close','element-name'); });
$("#element-name").on("click",function(e) { e.stopPropagation(); });
```

**Comment by Catlon** [comment]
This still closes my sidr panel even when I click in the menu.
Is there something missing?

**Comment by ancDev** [comment]
#screen-sidr-toggle {
  display: none;
  overflow: none;
  width: 100%;
  height: 100vh;
  z-index: 1;
  position: fixed;
  top: 0;
  background-color: rgba(0,0,0,.4);
}			

$('#sidr-menu').click( function() {
	$('#screen-sidr-toggle').css('display', 'block').click( function() {
		$.sidr('close');
		$(this).css('display', 'none');
	});
});

**Comment by artberri** [comment]
Did you try what is recommended in #111 ?

~~~ js
    $("body").on("click",function(e) {
        $.sidr('close','main-menu');
    });

    $("#main-menu").on("click",function(e) {
        e.stopPropagation();
    });
~~~
