### ISSUE TITLE
on Resize from desktop to mobile vew

### ISSUE THREAD

**Issue by abdurrahu001** [artberri/sidr#281]
On the following scenario, i am not able to open the side menu on clicking the button.

Steps to reproduce:
1. In mobile view, Click to open the side menu.
2. Without closing the menu, change the device in desktop view, where i had written custom changes in js to not show the side menu.
3. Then upon changing the view back to mobile, when i click on the button to open the menu, it is not calling the js at all.

Kindly provide me a solution for this.

**Comment by artberri** [comment]
I'm not sure what you mean but you can do whatever on windows resize:

~~~ js
    $(window).on('resize', function () {
      $.sidr('close', name);
    });
~~~
