### ISSUE TITLE
how to displace toggle ? 

### ISSUE THREAD

**Issue by marielemoal** [artberri/sidr#284]
Hi everyone, I'm using sidr and I'm very happy with it. But the final user of the website doesn't want the body to be displaced when sidr opens. Since I'm not an expert of jquery, I can't make the menu toggle move anyway (if the body doesn't move, when the sidr is open the toggle is hidden behind it). Do I have to enter a specific code in the onOpen and onClose functions ? 
when I replace the following part of the jquery.sidr.min.js : 
"body",displace:!1,onOpen:function(){},onClose:function(){}
by this : 
onOpen:function(){$("#side-menu").css({"padding-right": "200px"});},onClose:function(){$("#side-menu").css({"padding-right": "0"});}
It doesn't work but I guess I'm mistaking...
Thanks
Marie

**Comment by artberri** [comment]
You should not modify the original file. It's better to use the options.  Just pass the `displace: false` option on inicialization.
