### ISSUE TITLE
Close menu when click outside 

### ISSUE THREAD

**Issue by PixelT** [artberri/sidr#288]
When the menu is open, it should be possible to close it by click outside the menu container ( body etc. )

**Comment by artberri** [comment]
Hi @PixelT ,

You can implement that by your self, there is an example in the examples folder:
[https://github.com/artberri/sidr/blob/master/examples/nodisplaced-menu-with-close-options.html](https://github.com/artberri/sidr/blob/master/examples/nodisplaced-menu-with-close-options.html)

Kind Regards.
