### ISSUE TITLE
background Image disappers

### ISSUE THREAD

**Issue by DerExilant** [artberri/sidr#291]
Hi, I saw, someone had the same problem in 2015 and I also do. I defined the background image once for the body and then for the html tag. Both definitions do not change anything. Since Sidr had been inserted into this page, the background image vanishes and reappears only after opening and closing the Navigation.
My actual Code:
html
	background-image: url('images/gelaenderbg.jpg')
	background-position: top center
	background-size: 100% 100%
	background-repeat: no-repeat

**Comment by artberri** [comment]
Hi @DerExilant ,

Which version of Sidr are you using? That problem is supposed to be solved. Before, we were resetting the html inline styles when the menu closes, but we are not doing it anymore.

Could you show us the source code also? HTML, CSS and JS. Or give us some URL were we can check it?

**Comment by DerExilant** [comment]
Hi artberri,
I'm using v. 2.0.0 of sidr. I'll attach files.
[plain.zip](https://github.com/artberri/sidr/files/132346/plain.zip)

**Comment by artberri** [comment]
Sorry @DerExilant but you send me a php file that makes an include of a `header.php` and a `footer.php` files that you didn't include, and is where you probably are including your css and js.

**Comment by DerExilant** [comment]
Sorry.. I included them into this zip
[plain-frewa.zip](https://github.com/artberri/sidr/files/136048/plain-frewa.zip)

**Comment by artberri** [comment]
Sorry for being late, try updating the version.
