### ISSUE TITLE
Not able to install sidr through npm

### ISSUE THREAD

**Issue by muthufmass** [artberri/sidr#293]
I am getting following error. I am in the latest version of nodejs - 5.6.0.

However, Sidr installs through bower

npm install sidr --save

> sidr@2.2.0 preinstall /xyz/node_modules/.staging/sidr-017894ab
> bundle install --path=vendor/bundle && npm install -g bower grunt-cli && bower install

sh: bundle: command not found
npm ERR! Darwin 15.3.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "sidr" "--save"
npm ERR! node v5.6.0
npm ERR! npm  v3.6.0
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn

npm ERR! sidr@2.2.0 preinstall: `bundle install --path=vendor/bundle && npm install -g bower grunt-cli && bower install`
npm ERR! spawn ENOENT
npm ERR!
npm ERR! Failed at the sidr@2.2.0 preinstall script 'bundle install --path=vendor/bundle && npm install -g bower grunt-cli && bower install'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the sidr package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     bundle install --path=vendor/bundle && npm install -g bower grunt-cli && bower install
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs sidr
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls sidr
npm ERR! There is likely additional logging output above.

Need some fix on npm package i guess.

**Comment by artberri** [comment]
Ouch, yes :(

Thank you @muthufmass for the report, I'll try to fix it ASAP. I make an error on the package with the last version and is trying to install some gems that are needed for developing. 

Sorry for the inconveniences.

**Comment by artberri** [comment]
@muthufmass new version released with the fix. Thank you again!
