### ISSUE TITLE
open multiple menus

### ISSUE THREAD

**Issue by thawkins** [artberri/sidr#294]
Im trying to add an adaptive element to my site where if the viewport width is greater than two thresholds, it automatically opens the menus, its opening in overlap mode, but the design is fixed in such as way the menu opens into the white borders on each side. 

for one size break point, i would like to open just one menu, but for another i would like to open both. However if i open a menu the other one automatically closes. Is there any simple way to programmaticly disable that behavior, ie an option that turns it off.

**Comment by artberri** [comment]
It will be considered in the new version:
https://github.com/artberri/sidr/pull/181
https://github.com/artberri/sidr/tree/sidr3
