### ISSUE TITLE
ie8 problem

### ISSUE THREAD

**Issue by iografica** [artberri/sidr#296]
Seems that the plugin doesn't work with internet explorer 8, unfortunately most people still use ie8, which is the latest version compatible with it?

**Comment by artberri** [comment]
If we continue supporting ie8 they will never switch, so, we are not supporting it. Version 1.2.1 should work I guess.

Sorry for being late answering.

**Comment by Codepadawan** [comment]
I've found even including it on a page in IE (but not invoking it) causes errors in IE8
