### ISSUE TITLE
Sidr menu causes broken anchor links on site

### ISSUE THREAD

**Issue by mccawphoto** [artberri/sidr#297]
When I run my site through my link checker I get broken anchor link errors because of the sidr menu. In my report for the site it shows links like this as broken:

http://pepper.seequsdev.com/san-diego-services-area/#sidr-main

Any thoughts on how I can use sidr but fix the broken anchor links?

Thanks!

**Comment by artberri** [comment]
Stackoverflow is a better place for doubts. I'll close this as it seems too old.
