### ISSUE TITLE
Resource source of URL does not support numbers in name

### ISSUE THREAD

**Issue by hobodoompants** [artberri/sidr#299]
Having a source of http://comp2/sidebar.html does not pass as a valid url
It appears that having a number in the server name/domain name portion will cause the regex to kick out the url as invalid

**Comment by artberri** [comment]
Sorry for being late answering.

The problem are not the numbers, is that is not a valid domain (no TLD).

https://jsfiddle.net/hqqtg6nw/

Sorry about that.
