### ISSUE TITLE
Sidr menu to occupy full device size when open

### ISSUE THREAD

**Issue by bananamariap** [artberri/sidr#310]
Hi, 
Is it possible to push the sidr menu on a full width. Using the default sidr theme, the sidr menu is set to 260px? How can I make the sidr menu size 100% without overflowing.

**Comment by proscriptsell** [comment]
Hi
Yes it possible with simply edit css  you can try with bellow css 
`.sidr {
width: 500px;
}
.sidr.right {
	right: -500px
}
.sidr.left {
	left: -500px;
}`

Thanks

**Comment by artberri** [comment]
Thanks @proscriptsell I'll close this.

Anyway, Stackoverflow is a better place for doubts and implementation issues.
