### ISSUE TITLE
jquery.sidr.js:9 - Uncaught ReferenceError: require is not defined

### ISSUE THREAD

**Issue by brandensilva** [artberri/sidr#311]
It looks like you have pulled in Babel but after installing via bower its pulling from the src/jquery.sidr.js file and hitting this error on the import statements.

**Comment by easingthemes** [comment]
Also if you use it with npm:
`sidr.js:1 Uncaught SyntaxError: Unexpected token import`

**Comment by artberri** [comment]
I think that it's the same problem that is mentioned in #309. I'll try to solve it.
