### ISSUE TITLE
`name` attribute is misleading, should input check.

### ISSUE THREAD

**Issue by danielsokolowski** [artberri/sidr#312]
Should be renamed to `menuID` or a graceful error should be thrown when one tries to use an invalid value like `MENU NAME`, just spend 1 hour trying to figure out why the menu was not sliding out - that value is the `id` attribute and is used in the click handler. 

Thanks for reading this and be great, 

![image](https://cloud.githubusercontent.com/assets/273413/18520465/edcbd4c6-7a75-11e6-860e-42a49cceaf93.png)

**Comment by artberri** [comment]
Sorry but this is a project that is live since 2013 and we have been using `name` from the beginning. I know that is not the best naming, but changing it now will break the API, which makes no sense.

I'll try to improve the documentation in order to clarify it and avoid problems like yours.

**Comment by danielsokolowski** [comment]
Thanks you kindly, just trying to think of the hairline of the next developer. Be great.
