### ISSUE TITLE
Unordered list inside sir is messed up

### ISSUE THREAD

**Issue by chitgoks** [artberri/sidr#314]
I added an unordered list with its own CSS inside the SIDR container. Problem is the resulting display is whacked.

SIDR has some CSS Properties on UL and LI and even if set all my CSS properties to !important, it does not work.

is there a way that the UL and LI CSS properties of SIDR will only affect within the elements involved? and not my elements that I added to the SIDR container?

**Comment by artberri** [comment]
Stackoverflow is a better place for doubts and implementation issues.
