### ISSUE TITLE
Links don't working when body moves

### ISSUE THREAD

**Issue by Julia1996** [artberri/sidr#316]
I was very surprised when I took my mobile phone, clicked on the links in the opened sidr menu and nothing happend. This poblem was only when menu was longer than height of screen. I spent about 4 hours to find out why it was occure. So I just hadn't moved body and everything had worked proper. 

Please, do something with this.

**Comment by artberri** [comment]
Stackoverflow is a better place for doubts and implementation issues (don't forget to provide your failing code).
