### ISSUE TITLE
Able to Scroll Right and Reveal Right Sidr Menu Without Clicking Button

### ISSUE THREAD

**Issue by althekiller** [artberri/sidr#317]
I am using both a left and right sidr menu on the same page.  On mobile (iOS) only, I am able to scroll the page to the right and it reveals the right sidr menu, despite not clicking the button to open it.  Left sidr menu behaves as it should and cannot be manually revealed by scrolling left.  I've been pulling my hair out trying to fix this but I'm having no luck, I'm hoping it is a CSS gremlin, but it is odd to only have it happening on mobile.

**Comment by artberri** [comment]
Stackoverflow is a better place for doubts and implementation issues (don't forget to provide your failing code).
