### ISSUE TITLE
pulls and pushes other content around

### ISSUE THREAD

**Issue by echolte** [artberri/sidr#321]
Left Menu when clicked quickly pulls my content div to the left and then pushes part way back. when closed does the same thing. Very jerky.
![capture](https://cloud.githubusercontent.com/assets/25373919/22358335/1607c800-e3f3-11e6-819a-acfcc208f486.JPG)

**Comment by artberri** [comment]
Stackoverflow is a better place for doubts and implementation issues (don't forget to provide your failing code).
