### ISSUE TITLE
Sidr Responsive Menu (Google Chrome)

### ISSUE THREAD

**Issue by Phuizour** [artberri/sidr#329]
Google chrome requires to clear cache every time you update css code.
for example i have a website on Drupal 8 and im updating a local.css file that overrides all css on the template. when i upload the updated version of the css file via FTP i will then need to clear the Google Chrome cache **EVERYTIME** i want to view the Sidr Responsive Menu on the mobile device version of Chrome. This of course doesn't happen in IE11 and im not sure about firefox as i haven't downloaded that.

If anyone has a fix for this please post it and hopefully the developers will fix this in the next update.

**Comment by artberri** [comment]
Stackoverflow is a better place for doubts and implementation issues (don't forget to provide your failing code).
