### ISSUE TITLE
sidr is removing one class and I need it so is there any solution so sidr doesn't remove it? or any other solution?

### ISSUE THREAD

**Issue by jengz** [artberri/sidr#330]
Ex : This is my Code
`<div class="social"><a href="#"><i class="fa fa-facebook"></i></a> <a href="#"><i class="fa fa-twitter"></i></a> <a href="#"><i class="fa fa-google-plus"></i></a> <a href="#"><i class="fa fa-instagram"></i></a></div>`

basically sidr convert this
`<div class="sidr-inner"><a href="#"><i class="fa fa-facebook"></i></a> <a href="#"><i class="fa fa-twitter"></i></a> <a href="#"><i class="fa fa-google-plus"></i></a> <a href="#"><i class="fa fa-instagram"></i></a></div>`

This is my function
` $('.bar').sidr({
        renaming: false,
	side: 'right',
	source: '.social',
});`

So i want like this
`<div class="sidr-inner social"><a href="#"><i class="fa fa-facebook"></i></a> <a href="#"><i class="fa fa-twitter"></i></a> <a href="#"><i class="fa fa-google-plus"></i></a> <a href="#"><i class="fa fa-instagram"></i></a></div>`

**Comment by Sjconsulting** [comment]
+1 it would be best if sidr took all classes and added them to the sidr-inner div, even if that meant prefixing with sidr-

**Comment by Sjconsulting** [comment]
Although it is possible to use .sidr-inner:nth-child() to style them

**Comment by artberri** [comment]
Stackoverflow is a better place for doubts and implementation issues (don't forget to provide your failing code).
