### ISSUE TITLE
Sidr is appending #sidr-0 in URL in first time and nothing happens

### ISSUE THREAD

**Issue by ravijo** [artberri/sidr#336]
I am using Sidr in my Drupal 7 website to create a responsive menu. I am using [Responsive Menus module](https://www.drupal.org/project/responsive_menus) with [Sidr library](https://www.berriart.com/sidr/). I have enabled Aggregate JavaScript and CSS files also. There has been already a menu for big screens such as Desktop etc and I have passed the id of this element (which is` #main-menu`) to Sidr, as suggested in the documentation. I have not installed [jQuery Update](https://www.drupal.org/project/jquery_update) module. Hence I believe I am using default jQuery provided by Drupal 7 framework. Running `console.log(jQuery.fn.jquery);` returns 1.4.4 in Chrome console in my PC .

The problem is that in the mobile device, whenever I touch menu button, it appends `#sidr-0` in URL as `www.example.com/#sidr-0`  and nothing happens at first attempt. However, it starts working smoothly from second time onwards. Also from second time onwards, nothing has been appended to the URL and it remains same i.e. `www.example.com`

This happens on all devices (i have checked already android and iPhone ). It seems to me that it is loading sidr library at first attempt and once it is download to the device, it starts working fine. 

Is there any workaround for this issue? I certainly don't like any user to touch menu icon twice. It gives a negative impression as well.

**Comment by artberri** [comment]
Stackoverflow is a better place for doubts and implementation issues (don't forget to provide your failing code). (I'm not keen on Drupal, sorry).
