### ISSUE TITLE
parent menu not clickable

### ISSUE THREAD

**Issue by WebHuntInfotech** [artberri/sidr#337]
Hello.

I'm creating a WordPress site with twitter bootstrap.

And want to use sidr side responsive menu for my WordPress site.

But unfortunately when i'm using a sidr side responsive menu with my WordPress site parent menu not clickable.

Can i use sidr side responsive menu with bootstrap.min.js.

Because when i commented bootstrap.min.js it's working but when i use bootstrap.min.js it's not working.

I really like your sidr side responsive menu a lot.

So please provide the best solution asap.

Thank You

**Comment by WebHuntInfotech** [comment]
Hello,

Anybody is here.

did you have any solution ?

So i can complete my project.

Thank You

**Comment by artberri** [comment]
Stackoverflow is a better place for doubts and implementation issues (don't forget to provide your failing code).

I'm not providing free support for your projects, sorry.
