### ISSUE TITLE
Hide sidr when clicking / touching outside the sidr

### ISSUE THREAD

**Issue by jigarius** [artberri/sidr#338]
## Expected Behavior
After opening is sidr, many people click / touch outside the sidr expecting it to close.

## Current Behavior
When clicking outside an open sidr, the sidr remains open.

## Possible Solution
Implement a click listener on the document `body`. This listener should track clicks and if a Sidr is open, then it should use something like:
```
if (jQuery.sidr('status').opened && 1 === jQuery(event.target).closest('.sidr').length) {
  jQuery.sidr('close', jQuery.sidr('status').opened);
}
```

## Steps to Reproduce

1. Open a sidr by clicking the relevant trigger button
2. Click / touch outside the sidr
3. You will see that the sidr remains open

**Comment by artberri** [comment]
Related to already closed issues: #288 #280 

That feature will not be implemented. You can easily implement it by your self like is shown in this is example:
https://github.com/artberri/sidr/blob/v2.2.1/examples/nodisplaced-menu-with-close-options.html

Or try adding the body listener on your own code. We try to keep the library as simple and tiny as possible.
