### ISSUE TITLE
Choppy animation

### ISSUE THREAD

**Issue by jdifelice** [artberri/sidr#4]
Nice work on the plugin.  I have noticed, however, that the sliding animation is choppy.  Is there a way to make it more smooth?  Is there an option I've missed?

I am running the plugin within a PhoneGap build on an iPhone 5 running iOS 6.1.2, but it's choppy even when viewed in desktop Chrome v20.0.1132.47.

Thanks.

**Comment by aaroncrawford** [comment]
This should be addressed - relying on jquery for animation doesn't invoke the GPU.

**Comment by artberri** [comment]
It will be added when implementing CSS animations

https://github.com/artberri/sidr/pull/30

**Comment by Adam-Reynolds** [comment]
Possible workaround is to use velocityJS and point $.animate to $.velocity.. same syntax, better performance.

**Comment by artberri** [comment]
CSS transitions will be added in the next Sidr version. You can check it in the 2bc6799bb78165750166bea378c0629ea29278e7 commit (and the following ones).

Than you all for your support.
