### ISSUE TITLE
Jquery Sidr Menu with Smoothscroll

### ISSUE THREAD

**Issue by ncsquare** [artberri/sidr#50]
I am using the sidr menu with a smooth scroll script and I would like the menu to close when an anchor link is clicked and then smooth scroll to location on the page. Has anyone had any luck with this? This is the smooth scroll script: http://demos.flesler.com/jquery/scrollTo/

Thanks

**Comment by artberri** [comment]
You can just close the menu when someone click on a link inside it:

~~~ js
$('.sidr li a').click(function () {
    $.sidr('close', 'sidr-name');
});
~~~
