### ISSUE TITLE
Flash of content on load

### ISSUE THREAD

**Issue by justiny** [artberri/sidr#60]
Having some difficulty resolving a flash of the sidr content on page load.  Is there a way to hide that content while it loads?

Thanks! 
Justin

**Comment by knotnow** [comment]
Thanks !

**Comment by priisc** [comment]
Hi hi! For some reason it doesn't work anymore with the latest version of SIDR? anyone experimented this issue?

**Comment by beatsforthemind** [comment]
I am also getting the flash on page load with v2.2.1. Add inline display: none; keeps the sidr div hidden through open.

**Comment by DuckDivers** [comment]
I see this happening with ios, but not chrome on android.  display:none; or visibility:hidden; keeps the sidr hidden.
