### ISSUE TITLE
Remove instance

### ISSUE THREAD

**Issue by crpr** [artberri/sidr#61]
Is there any way to destroy a sidr instance?

**Comment by mehmetkurt** [comment]
After you remove the instance you want to add it again. How can I do? The sample code below. I will be glad if you help me.

`(function () {
    $(window).resize(function () {
        sidr();
    });

    var sidr = function () {
        var docWidth = $(document).innerWidth();
        if (docWidth <= 992) {
            $('#open-navigation').sidr({
                name: 'sidr-main',
                source: '#main-nav'
            });

            $('body').swipe({
                swipeLeft: function () {
                    $.sidr('close', 'sidr-main');
                },
                swipeRight: function () {
                    $.sidr('open', 'sidr-main');
                },
                threshold: 0
            });
        }
        else { $('#sidr-main').remove(); }
    };
})(jQuery);`

**Comment by LubosRemplik** [comment]
Is there away to reconstruct original navigation after I remove sidr?

**Comment by artberri** [comment]
Stackoverflow is a better place for doubts and implementation issues (don't forget to provide your failing code).
