### ISSUE TITLE
Windows Phone Issues

### ISSUE THREAD

**Issue by residentmeevil** [artberri/sidr#78]
I'm having some issues with Sidr on Windows Phone's running both IE9 and IE10.

When the user clicks the menu button, the entire page is pushed off the right hand side of the screen, including the sidr menu.

![sidrissue](https://f.cloud.github.com/assets/5236495/1279547/249efb5c-2f3a-11e3-8d4c-ce70b031156e.jpg)

I've only been able to replicate this error on a Windows Phone at the moment. The plugin works on every other mobile browser I've tested so far.

Any help would be massively appreciated in solving this issue. Thanks!

**Comment by artberri** [comment]
Not supporting Windows Phone, I can not get a device to do it. Let me know if the bug is still there or if you have a fix
