### ISSUE TITLE
Toogle not opening on first click

### ISSUE THREAD

**Issue by josholdham** [artberri/sidr#8]
Hi - great plugin.

Only issue is that on first click of my selector element, nothing happens to the .sidr element. The callback function runs, but the sidr does not appear until the second click. I have used the selector implementation - so assume it's the 'toogle' method. From the second click onwards, the .sidr element toggles as expected.

I tried using the generic implementation too, with the open and close methods manually toggled, but I couldn't get that to work at all (again, the 'complete' callback function ran, but not toggling of the .sidr element)

Apologies if I'm being stupid. Any more details please let me know.

Josh

**Comment by wpexplorer** [comment]
Just make sure whatever you named the sidebar to hide it with CSS:

```
// JS
$( '.mobile-toggle-button' ).sidr({
name: 'sidr-main',
source: '#navigation'
});
```

```
/*css*/
#sidr-main { display: none; }
```

**Comment by artberri** [comment]
@wpexplorer gave you the proper answer. You need to hide the sidebar on CSS.
