### ISSUE TITLE
An option to prevent just the .sidr-class prefix from being added

### ISSUE THREAD

**Issue by jesserosenfield** [artberri/sidr#86]
Is there an option to prevent this from happening? Classes are not unique and don't need a  prefix to validate the HTML. They can be easily differentiated by using a descending selector. I just want to prevent class renaming, not the ID.

Thank you!

**Comment by santoshverma001** [comment]
artberri: thanks dear it's working :+1:

**Comment by santonum** [comment]
Hello,
I think there is still an issue with this solution : defining `renaming` to `false` doesn't rename classes, ok, but it doesn't rename ids either !
We sometimes need to keep classes but we MUST rename ids because they must be unique.
You should create `renamingClasses` and `renamingIds` options, or add `keepClasses` option to `renaming` option.

**Comment by schmelik** [comment]
instead of using the id, can you put the id into a class? you can still make your calls according to a unique class.

**Comment by santonum** [comment]
No, I don't talk about the whole menu ID. Every `<ul>` in my source menu has got an `id` to use Bootstrap3 Collapse features, target identified with `data-target="#id"`. So I don't want to rename `ul` classes like `btn`, `collapse`, ... but all the IDs MUST be renamed to be unique.

**Comment by schmelik** [comment]
ahh, bootstrap..

is it the bootstrap collapse that is not working or sidr? it could be a race issue where bootstrap is loading before sidr.

**Comment by santonum** [comment]
I never wrote that something was not working using Sidr AND Bootstrap.
Just that because of the `renaming` option that renames classes as ids, I need to write a jquery script to delete the Sidr's classes prefixes !!

 ```
$(".sidr-inner .sidr-class-collapse").addClass( "collapse").removeClass("sidr-class-collapse");
$(".sidr-inner .sidr-class-btn").addClass( "btn").removeClass("sidr-class-btn");
$(".sidr-inner .sidr-class-btn-default").addClass( "btn-default").removeClass("sidr-class-btn-default");
...
```

Isn't it stupid ???
So some users need to rename IDs without renaming classes.
