### ISSUE TITLE
Close sidr when browser resized leaves behind inline body styles

### ISSUE THREAD

**Issue by spib** [artberri/sidr#93]
Hey Guys

$.sidr('close') doesn't have any effect if the element is not visible (which makes sense). However, if this is used with a responsive design and media queries, you can get into a situation where the browser has been resized with sidr open, the media queries hide the menu but it leaves behind the inline styles on the body.

I have this jquery in place to close the sidr if the browser has moved beyond the mobile break point but it has no effect because of the :visible check.

````javascript
$(window).bind('resize', function () {
        
        if($('body').hasClass('sidr-open') && $(window).width() >= 768) {
            $.sidr('close');
        }

    });
````

Any ideas on the correct way to achieve this?

**Comment by skyyip** [comment]
$(window).bind('resize', function () {
  if($('body').hasClass('sidr-open') && $(window).width() >= 768) {
    $.sidr('close', 'sidr-main');
  }
});

**Comment by artberri** [comment]
You can use $(window).resize(function () ... to implement the behaivour you want.
