### ISSUE TITLE
problem on Google Chrome localhost only

### ISSUE THREAD

**Issue by angeltcho** [artberri/sidr#98]
Hello,
First of all, I'd like to point that Sidr is an excellent plugin. So I congratulate the author :+1: 
I've been using the 1.1.1 version without any major problem.
Now I'm testing the 1.2.1 package and so things are quite annoying.

1.2.1 Package is installed on the same localhost as 1.1.1
But while using it on localhost with Chrome browser. Nothing works.
It tested it locally on Firefox, IE and Safari and it works fine.
It tested it remotely on Firefox, IE and Safari, Chrome Android and it works fine too.
every extensions are disabled.
So why doesn't it work locally on Chrome ?
Javascript console is silent, no error reported :-(

My Chrome version is : 31.0.1650.57 (Build officiel 235101) m

Thank you for your help.

Regards

**Comment by artberri** [comment]
Preparing a new version with a fix for this https://github.com/artberri/sidr/tree/reborn
